export const ENHANCEMENT_CATEGORY = [
  'defense-debuff',
  'to-hit-debuff',
  'taunt',
  'confuse',
  'healing',
  'defense-buff',
  'resist-damage',
  'intangibility',
  'sleep',
  'slow',
  'hold',
  'stun',
  'immobilize',
  'fear',
  'endurance-modification',
  'endurance-reduction',
  'recharge-reduction',
  'interrupt-duration',
  'accuracy',
  'to-hit-buff',
  'damage',
  'knockback',
  'run-speed',
  'jump',
  'fly-speed',
  'range',
] as const

export type EnhancementCategory = typeof ENHANCEMENT_CATEGORY[number]
