name: Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: lts/krypton
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: 'dist'
          path: 'dist'
          if-no-files-found: error

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          files: 'dist/*'

      - name: Publish
        run: npm publish --provenance --access public
